import FoodCard from "./FoodCard";

const iranianFood = [
  {
    id: "1",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_01.png",
    title: "کوفته برنجی",
    description: "برنج سبزی کوفته لپه آرد نخودچی، گردو و زرشک و آلو پیاز",
    highPrice: "180000",
    discount: "%35",
    finalPrice: 145000,
    star: "some star",
  },
  {
    id: "2",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_02.png",
    title: "کشک بادمجان",
    description: "بادمجان، کشک، نعناع خشک، مغز گردو، سیر، پیاز",
    highPrice: "",
    finalPrice: 95000,
    star: "some star",
  },
  {
    id: "3",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_03.png",
    title: "میرزا قاسمی",
    description: "بادمجان، گوجه فرنگی، تخم مرغ، سیر، رب گوجه فرنگی",
    highPrice: "165000",
    discount: "%10",
    finalPrice: 142500,
    star: "some star",
    filter: "پیشنهاد ویژه",
    mostSale: true,
  },
  {
    id: "4",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_04.png",
    title: "باقلاقاتوق",
    description: "پاچ باقلا، شوید خشک، کره، سیر، تخم مرغ",
    highPrice: "205000",
    discount: "%30",
    finalPrice: 180000,
    star: "some star",
    filter: "پیشنهاد ویژه",
    mostSale: true,
  },
  {
    id: "5",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_05.png",
    title: "فلافل",
    description: "نخود، پیاز، تخم گشنیز، سیر، جعفری، سیب زمینی",
    highPrice: "",
    finalPrice: 80000,
    star: "some star",
    mostSale: true,
  },
  {
    id: "6",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_06.png",
    title: "کله جوش",
    description: "کشک، گردو، پیاز، نعناع خشک",
    highPrice: "210000",
    discount: "%5",
    finalPrice: 20300,
    star: "some star",
    filter: "پیشنهاد ویژه",
    mostSale: true,
  },
  {
    id: "7",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_07.png",
    title: "بورانی بادمجان",
    description: "بادمجان قلمی، ماست چکیده، سیر، روغن زیتون، مغز گردو",
    highPrice: "170000",
    discount: "%22",
    finalPrice: 148000,
    star: "some star",
    score: "(۷۵ امتیاز)",
    filter: "پیشنهاد ویژه",
    mostSale: true,
  },
  {
    id: "8",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_08.png",
    title: "بادمجان شکم‌پر",
    description: "بادمجان، پیاز، گوجه فرنگی	، سبزی خشک",
    highPrice: "150000",
    discount: "%18",
    finalPrice: 136000,
    star: "some star",
    score: "(۳۲ امتیاز)",
    filter: "پیشنهاد ویژه",
    mostSale: true,
  },
  {
    id: "9",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_09.png",
    title: "دلمه برگ کلم",
    description: "کلم برگ، برنج، لپه پخته، پیاز، سبزی معطر رب",
    highPrice: "220000",
    discount: "%8",
    finalPrice: 209000,
    star: "some star",
    score: "(۵۲ امتیاز)",
    filter: "پیشنهاد ویژه",
  },
  {
    id: "10",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_10.png",
    title: "دلمه برگ مو",
    description: "پیاز، برنج، لپه، سبزی دلمه، سرکه",
    highPrice: "",
    finalPrice: 195000,
    star: "some star",
  },
  {
    id: "11",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_11.png",
    title: "کوکو سبزی",
    description: "تخم مرغ، گردو، سیر، آرد، روغن مایع سبزی کوکویی",
    highPrice: "300000",
    discount: "%10",
    finalPrice: 270000,
    star: "some star",
    filter: "پیشنهاد ویژه",
  },
  {
    id: "12",
    category: "غذاهای ایرانی",
    image: "/assets/images/foodImages/iranian_food/iranian_food_12.png",
    title: "کوکو سیب‌زمینی",
    description: "عدس، سیب زمینی، پیاز متوسط، تخم مرغ، پودر سیر، آرد سوخاری",
    highPrice: "135000",
    discount: "%20",
    finalPrice: 105000,
    star: "some star",
    filter: "پیشنهاد ویژه",
  },
];

const notIranianFood = [
  {
    id: "13",
    category: "غذاهای غیر ایرانی",
    image: "/assets/images/foodImages/not_iranian_food/not_iranian_food_01.png",
    title: "پاستا سبزیجات",
    description: "پاستا، قارچ، گوجه، کدوی خوردشده، پیاز خلالی‌شده",
    highPrice: "۱۷۵٬۰۰۰",
    discount: "%۲۰",
    finalPrice: 140000,
    star: "some star",
  },
  {
    id: "14",
    category: "غذاهای غیر ایرانی",
    image: "/assets/images/foodImages/not_iranian_food/not_iranian_food_02.png",
    title: "پاستا بلونز",
    description:
      "اسپاگتی، گوشت چرخ کرده، هویج، ساقه کرفس، گوجه فرنگی، سیر، پیاز، پنیر پارمزان",
    highPrice: "۱۷۰٬۰۰۰",
    discount: "%۱۲",
    finalPrice: 160000,
    star: "some star",
  },
  {
    id: "15",
    category: "غذاهای غیر ایرانی",
    image: "/assets/images/foodImages/not_iranian_food/not_iranian_food_03.png",
    title: "راتاتویی",
    description:
      "بادمجان، گوجه فرنگی، کدو سبز، پیاز، رب گوجه فرنگی، روغن زیتون، پنیر پارمزان",
    highPrice: "۱۸۰٬۰۰۰",
    discount: "%۴۵",
    finalPrice: 95000,
    star: "some star",
    score: "(۴۳ امتیاز)",
  },
  {
    id: "16",
    category: "غذاهای غیر ایرانی",
    image: "/assets/images/foodImages/not_iranian_food/not_iranian_food_04.png",
    title: "لازانیا",
    description:
      "لازانیا، قارچ، ریحان تازه، جعفری تازه، گوجه فرنگی، پنیر پیتزا، بادمجان",
    highPrice: "",
    finalPrice: 150000,
    star: "some star",
    score: "(۴۸ امتیاز)",
  },
  {
    id: "17",
    category: "غذاهای غیر ایرانی",
    image: "/assets/images/foodImages/not_iranian_food/not_iranian_food_05.png",
    title: "سوشی",
    description:
      "جلبک دریایی/ نوری، برنج کته، سرکه سفید (یا سرکه برنج)، شکر، نمک دریا",
    highPrice: "۱۰۰٬۰۰۰",
    discount: "%۱۵",
    finalPrice: 85000,
    star: "some star",
    score: "(۷۰ امتیاز)",
  },
  {
    id: "18",
    category: "غذاهای غیر ایرانی",
    image: "/assets/images/foodImages/not_iranian_food/not_iranian_food_06.png",
    title: "پاکورا سبزیجات",
    description: "گرام ماسالا، پودر کاری، سیر له شده، ،گشنیز خرد شده",
    highPrice: "۱۲۵٬۰۰۰",
    discount: "%۸",
    finalPrice: 110000,
    star: "some star",
    score: "(۷۵ امتیاز)",
  },
  {
    id: "19",
    category: "غذاهای غیر ایرانی",
    image: "/assets/images/foodImages/not_iranian_food/not_iranian_food_07.png",
    title: "کالزونه اسفناج",
    description:
      "اسفناج، قارچ، پنیر موزارلا یا پنیر پیتزا، پنیر ریکوتا یا پنیر خامه ای، پیاز، سیر، روغن زیتون",
    highPrice: "۱۹۰٬۰۰۰",
    discount: "%۱۷",
    finalPrice: 177000,
    star: "some star",
    score: "(۶۲ امتیاز)",
  },
  {
    id: "20",
    category: "غذاهای غیر ایرانی",
    image: "/assets/images/foodImages/not_iranian_food/not_iranian_food_08.png",
    title: "پالاک پنیر ",
    description: "پنیر، اسفناج، گوجه، پیاز، سیر ",
    highPrice: "۲۰۰٬۰۰۰",
    discount: "%۱۵",
    finalPrice: 180000,
    star: "some star",
  },
];

const pizza = [
  {
    id: "21",
    category: "پیتزاها",
    image: "/assets/images/foodImages/pizza/pizza_01.png",
    title: "پیتزا روکولا",
    description:
      "اسفناج، سبزی روکولا، آرد، پودر مایه خمیر، روغن زیتون، خردل، سیر، پنیر موزارلا و ",
    highPrice: "۱۹۵٬۰۰۰",
    discount: "%۱۲",
    finalPrice: 188000,
    star: "some star",
    filter: "غذاهای محبوب",
  },
  {
    id: "22",
    category: "پیتزاها",
    image: "/assets/images/foodImages/pizza/pizza_02.png",
    title: "پیتزا بادمجان و زیتون",
    description:
      "بادمجان کوچک، روغن زیتون، پنیر موزارلا، پنیر پارمزان، برگ ریحان، گوجه فرنگی، سس گوجه فرنگی",
    highPrice: "",
    finalPrice: 150000,
    star: "some star",
    filter: "غذاهای محبوب",
  },
  {
    id: "23",
    category: "پیتزاها",
    image: "/assets/images/foodImages/pizza/pizza_03.png",
    title: "پیتزا سبزیجات و خامه",
    description:
      "نخود فرنگی پخته شده، ذرت نیم پز، فلفل دلمه‌ای رنگی، قارچ، سیر یا پیازچه خردشده",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۲۱",
    finalPrice: 185000,
    star: "some star",
    filter: "غذاهای محبوب",
  },
  {
    id: "24",
    category: "پیتزاها",
    image: "/assets/images/foodImages/pizza/pizza_04.png",
    title: "پیتزا قارچ",
    description:
      "قارچ، فلفل دلمه ای، رب گوجه فرنگی، پودر سیر، آویشن، مرزه، پنیر پیتزا گیاهی",
    highPrice: "۲۱۵٬۰۰۰",
    discount: "%۲۵",
    finalPrice: 175000,
    star: "some star",
    score: "(۳۳ امتیاز)",
    filter: "غذاهای محبوب",
  },
  {
    id: "25",
    category: "پیتزاها",
    image: "/assets/images/foodImages/pizza/pizza_05.png",
    title: "پیتزا پپرونی",
    description:
      "تافو، فلفل قرمز خشک شده، پودر دانه‌های خردل، دانه رازیانه، پاپریکا دودی، پودر سیر، شکر نارگیل، پودر بادیان رومی ",
    highPrice: "",
    finalPrice: 100000,
    star: "some star",
    score: "(۵۱ امتیاز)",
    filter: "غذاهای محبوب",
  },
  {
    id: "26",
    category: "پیتزاها",
    image: "/assets/images/foodImages/pizza/pizza_06.png",
    title: "پیتزا اسفناج",
    description: "اسفناج تازه، پیاز، سیر، پنیر پیتزا، قارچ",
    highPrice: "۲۸۰٬۰۰۰",
    discount: "%۱۰",
    finalPrice: 252000,
    star: "some star",
    filter: "غذاهای محبوب",
  },
  {
    id: "27",
    category: "پیتزاها",
    image: "/assets/images/foodImages/pizza/pizza_07.png",
    title: "پیتزا مارگاریتا",
    description: "گوجه فرنگی، ریحان، سیر، پنیر پیتزا",
    highPrice: "۱۶۵٬۰۰۰",
    discount: "%۱۳",
    finalPrice: 147000,
    star: "some star",
    filter: "غذاهای محبوب",
  },
  {
    id: "28",
    category: "پیتزاها",
    image: "/assets/images/foodImages/pizza/pizza_08.png",
    title: "پیتزا پنیر",
    description:
      "نان پیتزا، پنیر پیتزا، سس باربیکیو، گوجه فرنگی، سس کچاپ، سیر، روغن زیتون",
    highPrice: "۱۲۵٬۰۰۰",
    discount: "%۱۶",
    finalPrice: 105000,
    star: "some star",
    filter: "غذاهای محبوب",
  },
];

const sandwiches = [
  {
    id: "29",
    category: "ساندویچ‌ها",
    image: "/assets/images/foodImages/sandwich/sandwich_01.png",
    title: "ساندویچ کتلت",
    description:
      "سیب زمینی، لوبیا قرمز،  بلغور گندم، نعناع خشک، پودر زیره، پودر جوز هندی، گوجه فرنگی، روغن زیتون",
    highPrice: "۲۳۰٬۰۰۰",
    discount: "%۱۸",
    finalPrice: 205000,
    star: "some star",
    filter: "غذاهای محبوب",
  },
  {
    id: "30",
    category: "ساندویچ‌ها",
    image: "/assets/images/foodImages/sandwich/sandwich_02.png",
    title: "ساندویچ سوسیس",
    description: "سوسیس گیاهی، پیاز، سیب زمینی،  رب گوجه فرنگی",
    highPrice: "۲۰۵٬۰۰۰",
    discount: "%۳۵",
    finalPrice: 165000,
    star: "some star",
    filter: "غذاهای محبوب",
  },
  {
    id: "31",
    category: "ساندویچ‌ها",
    image: "/assets/images/foodImages/sandwich/sandwich_03.png",
    title: "ساندویچ کتلت کدو سبز",
    description: "کدو سبز، هویج، سیب زمینی، پیاز",
    highPrice: "",
    finalPrice: 145000,
    star: "some star",
  },
  {
    id: "32",
    category: "ساندویچ‌ها",
    image: "/assets/images/foodImages/sandwich/sandwich_04.png",
    title: "پنینی اسفناج",
    description:
      " قارچ، اسفناج، پیاز، پنیر پیتزا، خامه، پودر پاپریکا، گردو، سرکه بالزامیک، سس مایونز",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۱۵",
    finalPrice: 190000,
    star: "some star",
    score: "(۲۰ امتیاز)",
    filter: "پیشنهاد ویژه",
  },
  {
    id: "33",
    category: "ساندویچ‌ها",
    image: "/assets/images/foodImages/sandwich/sandwich_04.png",
    title: "ساندویچ همبرگر",
    description: " قارچ، پیاز، پنیر پیتزا، گردو، سرکه بالزامیک، سس مایونز",
    highPrice: "۲۱۰٬۰۰۰",
    discount: "%۱۵",
    finalPrice: 190000,
    star: "some star",
    score: "(۲۰ امتیاز)",
  },
];

export default function FoodList() {
  return (
    <div className="flex flex-col gap-y-3">
      {iranianFood.map((foodItem) => {
        return <FoodCard foodItem={foodItem} key={foodItem.id} />;
      })}
    </div>
  );
}
